dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven { url = 'https://maven.aliyun.com/repository/central' }
        maven { url = 'https://maven.aliyun.com/repository/public' }  
        maven { url = 'https://maven.aliyun.com/repository/google' }
        google()
        mavenCentral()
        // jcenter() deprecated - removed as it's shutting down, using mavenCentral() instead
        maven { url = 'https://jitpack.io' }
        maven {
            url = 'https://maven.zohodl.com'
        }
        maven { url = 'https://repo1.maven.org/maven2/' }
        flatDir {
            dirs 'android/libir/libs'
        }
    }
}
rootProject.name = "BucikaGSR"
include ':android:app'

// Core modules
include ':android:libapp'
include ':android:libir'
include ':android:libui'

// Additional modules from IRCamera
include ':BleModule'
include ':commonlibrary'
include ':component:CommonComponent'
include ':component:edit3d'
include ':component:house'
include ':component:pseudo'
include ':component:thermal-hik'
include ':component:thermal-ir'
include ':component:thermal-lite'
include ':component:thermal'
include ':component:thermal04'
include ':component:thermal07'
include ':component:transfer'
include ':component:user'
include ':libcom'
include ':libhik'
include ':libmenu'
include ':libmatrix'
include ':LocalRepo:libac020'
include ':LocalRepo:libcommon'
include ':LocalRepo:libirutils'
include ':RangeSeekBar'

