plugins {
    id 'com.android.library'
}

android {
    namespace = "com.topdon.ble"
    compileSdk rootProject.ext.android.compileSdk
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdk rootProject.ext.android.minSdk
        targetSdk rootProject.ext.android.targetSdk
        versionCode 1
        versionName "1.0"
        flavorDimensions "versionCode"
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    productFlavors {
        nj1000pro {

        }
        //AD900
        ultradiag {
        }
        //ArtiDiag900 ArtiDiag900Lite
        //ArtiDiag900 ArtiDiag900Lite 打包时需要修改DiagnoseModule和BluetoothModule 中的进程名称 进程名：com.topdon.diagnose.adliteservice  Constants.mAppVersion  此字段也需要修改
        artidiag900lite {
        }

        topscan{

        }

        keynow{

        }
    }
}

dependencies {
    // Remove direct AAR dependency from library module
    // api files('../android/app/libs/lms_international-3.90.009.0.aar')
    api 'androidx.appcompat:appcompat:1.6.1'
    api 'org.greenrobot:eventbus:3.3.1'
    api 'com.blankj:utilcodex:1.31.0'//工具包
    api 'com.google.code.gson:gson:2.10.1'
    api 'com.elvishew:xlog:1.11.0'
    api 'com.alibaba:fastjson:1.2.83'  // Add fastjson dependency
    implementation files('libs/ini4j-0.5.5.jar')
}