plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
    id 'com.google.devtools.ksp'
}

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
}

android {
    namespace = "com.topdon.component.thermal_ir"
    compileSdk = rootProject.ext.android.compileSdk

    defaultConfig {
        minSdk = rootProject.ext.android.minSdk
        targetSdk = rootProject.ext.android.targetSdk

        buildConfigField "String", "VERSION_NAME", "\"$rootProject.ext.android.versionName\""

    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures{
        dataBinding = true
    }
//    repositories {
//        flatDir {
//            dirs '../../libir/libs'
//        }
//    }

    flavorDimensions 'app'
    productFlavors {
        dev {
            dimension 'app'
        }
        beta {
            dimension 'app'
        }
        prod {
            dimension 'app'
        }
        prodTopdon {
            dimension 'app'
        }
        insideChina {
            dimension 'app'
        }
        prodTopdonInsideChina {
            dimension 'app'
        }
    }
}

dependencies {
    implementation(name: 'opengl_1.3.2_standard', ext: 'aar')
    implementation(name: 'library_1.0', ext: 'aar')

    implementation project(':android:libapp')
    implementation project(':libcom')
    implementation project(':android:libir')
    implementation project(':libmenu')
    implementation project(':android:libui')
    implementation project(':component:house')
    implementation project(':component:pseudo')

    // ARouter and other optional dependencies commented out for core functionality
    // ARouter and other optional dependencies commented out for core functionality
    // kapt 'com.alibaba:arouter-compiler:1.5.2'
    // api Deps.lottie
    api 'com.github.anzaizai:EasySwipeMenuLayout:1.1.4'

    //     // api Deps.compass_sense
    //     // api Deps.compass_core

    // gsy player
    implementation "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.4"
    implementation "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.4"
    implementation "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv64:v8.1.4"
}