coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
      android:
        target: 60%
        threshold: 5%
        paths:
          - "AndroidApp/src/main/"
      python:
        target: 75%
        threshold: 5%
        paths:
          - "PythonApp/src/"
    patch:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

flags:
  android:
    paths:
      - AndroidApp/src/main/
    carryforward: false
  python:
    paths:
      - PythonApp/src/
    carryforward: false

ignore:
  - "AndroidApp/src/test/"
  - "AndroidApp/src/androidTest/"
  - "PythonApp/tests/"
  - "PythonApp/src/tests/"
  - "**/test_*"
  - "**/*_test.py"
  - "**/build/"
  - "**/generated/"
  - "**/.gradle/"
  - "**/node_modules/"
  - "tools/"
  - "scripts/"
  - "docs/"
  - "examples/"

comment:
  layout: "reach,diff,flags,files,footer"
  behaviour: default
  require_changes: false

github_checks:
  annotations: true