name: gsr-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9,<3.13
  - pyqt=5.15.*
  - opencv
  - pillow
  - numpy>=1.26.0,<2.0.0
  - scipy
  - matplotlib
  - pandas
  - requests
  - websockets
  - pytest
  - pytest-cov
  - flake8
  - black
  - pip
  - pytest-mock
  - pytest-qt
  - mypy
  - bandit
  - memory-profiler
  - psutil
  - isort
  - pre-commit
  - sphinx
  - sphinx-rtd-theme
  - pyshimmer
  - bleak
